import ProfileSidebar from "./ProfileSidebar";



// Metadata for the page
export const metadata = {
    title: "Profile",
    description: "Generated by create next app",
};



export default function ProfileLayout({ children }) {

    return (
        <div className="flex">
            <ProfileSidebar />

            <main className="  flex-1 h-screen overflow-y-auto scrollbar-hidden bg-gray-200 py-16 md:py-10 px-4">
                {children}
            </main>
        </div>
    );
}
