
import Sidebar from "./Sidebar";

// Metadata for the page
export const metadata = {
    title: "Online Exam Services",
    description: "Generated by create next app",
};



export default function ServicesLayout({ children }) {

    return (
        <div className="flex">
            <Sidebar />

            <main className=" flex-1 h-screen overflow-y-auto scrollbar-hidden bg-gray-200 p-4">
                {children}
            </main>
        </div>
    );
}
